### ISSUE TITLE
Links for data broken

### ISSUE THREAD

**Issue by pesekon2** [GISMentors/grass-gis-workshop-jena#1]
[Links](https://github.com/GISMentors/grass-gis-workshop-jena/blob/master/index.rst?plain=1#L137-L140)  to data for the workshop in Jena are broken. Probably due to the change of websites... Anyways, they are all redirected to <https://geo.fsv.cvut.cz/gwiki/Studijn%C3%AD_program_Geod%C3%A9zie_a_kartografie>

**Comment by landam** [comment]
Fixed by e07330ed5163796bb6a487e54b6bd157f81104c3
